kind: Service
apiVersion: v1
metadata:
  name: customer-services
spec:
  selector:
    app: customer-services
  ports:
    - protocol: TCP
      port: 7000
      #nodePort: 30084
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-services
spec:
  selector:
    matchLabels:
      app: customer-services
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: customer-services
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer-services
    spec:
      containers:
        - name: customer-services
          image: 7039402000/customer-services:latest
          imagePullPolicy: Always
